# Generated by Django 4.1.5 on 2023-01-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('id',), 'verbose_name': 'Курсы', 'verbose_name_plural': 'Курсы'},
        ),
    ]
