# Generated by Django 4.1.5 on 2023-01-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='techer_image/', verbose_name='Фотография учителя')),
                ('name', models.CharField(max_length=255, verbose_name='Имя учителя')),
                ('work', models.CharField(max_length=255, verbose_name='Должность учителя')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=255, verbose_name='Почта учителя')),
            ],
            options={
                'verbose_name': 'Наша команда',
                'verbose_name_plural': 'Наша команда',
            },
        ),
    ]
