# Generated by Django 4.1.5 on 2023-01-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='faceebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='teams',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='teams',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='teams',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
    ]
