# Generated by Django 4.1.5 on 2023-01-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_teams_faceebook_teams_instagram_teams_telegram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='faceebook',
        ),
    ]
