# Generated by Django 4.1.5 on 2023-01-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image', models.ImageField(upload_to='slide_image', verbose_name='Фотография слайда')),
                ('name_slide', models.CharField(max_length=255, verbose_name='Название  слайда')),
                ('description_slide', models.TextField(verbose_name='Описание слайда')),
            ],
            options={
                'verbose_name': 'Слайды',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.AlterModelOptions(
            name='settins',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
    ]
