# Generated by Django 4.1.5 on 2023-01-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_slides_alter_settins_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='name_slide',
            field=models.TextField(verbose_name='Название  слайда'),
        ),
    ]
