# Generated by Django 4.1.5 on 2023-01-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_slides_name_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='description_slide1',
            field=models.TextField(default=1, verbose_name='Описание  первого слайда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slides',
            name='name_slide1',
            field=models.TextField(default=1, verbose_name='Название  первого  слайда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slides',
            name='slide_image1',
            field=models.ImageField(default=1, upload_to='slide_image', verbose_name='Фотография первого  слайда'),
            preserve_default=False,
        ),
    ]
