# Generated by Django 4.1.5 on 2023-01-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_remove_slides_description_slide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='It',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание!')),
                ('image', models.ImageField(upload_to='it', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'ПОЧЕМУ IT - ЭТО КРУТО?',
                'verbose_name_plural': 'ПОЧЕМУ IT - ЭТО КРУТО?',
            },
        ),
    ]
