# Generated by Django 4.1.5 on 2023-01-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_it'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=255, verbose_name='Учителя')),
                ('students', models.CharField(max_length=255, verbose_name='Ученики')),
                ('course', models.CharField(max_length=255, verbose_name='Курсы')),
                ('office', models.CharField(max_length=255, verbose_name='Офисы')),
            ],
            options={
                'verbose_name': 'Geektech в цифрах',
                'verbose_name_plural': 'Geektech в цифрах',
            },
        ),
    ]
