# Generated by Django 4.1.5 on 2023-01-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылка '},
        ),
    ]
