# Generated by Django 4.1.5 on 2023-01-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_contact_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_detail',
        ),
    ]
